name: linting, testing, build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version}}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: unit testing
        run: npm run unit
      - name: chromatic (screenshot) testing
        run: npm run chromatic
